name: istudyadmin
description: "A comprehensive admin panel for iStudy education management system"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^7.6.4

  # Network & API
  dio: ^5.3.2

  # Local Storage
  flutter_secure_storage: ^9.0.0

  # JSON Serialization
  json_annotation: ^4.8.1

  # UI & Formatting
  intl: ^0.20.2
  month_year_picker: ^0.5.0
  cupertino_icons: ^1.0.2

  # Icons
  material_design_icons_flutter: ^7.0.7296

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

  # Linting
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Assets
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # # Fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf
  #       - asset: fonts/Roboto-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Roboto-Bold.ttf
  #         weight: 700
